// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeminaPro.Data;

#nullable disable

namespace SeminaPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512170000_AddPaymentColumnsToInscription")]
    partial class AddPaymentColumnsToInscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SeminaPro.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AffichageConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateFacture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactureNumero")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeminaireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SeminaireId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("SeminaPro.Models.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeminaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecialiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SeminaireId");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSeminaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreMaximal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tarif")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Seminaires");
                });

            modelBuilder.Entity("SeminaPro.Models.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("SeminaPro.Models.Inscription", b =>
                {
                    b.HasOne("SeminaPro.Models.Participant", "Participant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeminaPro.Models.Seminaire", "Seminaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("SeminaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Seminaire");
                });

            modelBuilder.Entity("SeminaPro.Models.MediaFile", b =>
                {
                    b.HasOne("SeminaPro.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SeminaPro.Models.Seminaire", null)
                        .WithMany()
                        .HasForeignKey("SeminaireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SeminaPro.Models.Specialite", null)
                        .WithMany()
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.HasOne("SeminaPro.Models.Specialite", "Specialite")
                        .WithMany("Participants")
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.HasOne("SeminaPro.Models.Specialite", "Specialite")
                        .WithMany("Seminaires")
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("SeminaPro.Models.Specialite", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Seminaires");
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
