// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeminaPro.Data;

#nullable disable

namespace SeminaPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SeminaPro.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AffichageConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeminaireId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SeminaireId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Participants");

                    b.HasDiscriminator<string>("ParticipantType").HasValue("Participant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSeminaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreMaximal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tarif")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Seminaires");
                });

            modelBuilder.Entity("SeminaPro.Models.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("SeminaPro.Models.Industriel", b =>
                {
                    b.HasBaseType("SeminaPro.Models.Participant");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEntreprise")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.ToTable("Participants", (string)null);

                    b.HasDiscriminator().HasValue("Industriel");
                });

            modelBuilder.Entity("SeminaPro.Models.Universitaire", b =>
                {
                    b.HasBaseType("SeminaPro.Models.Participant");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomUniversite")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.ToTable("Participants", (string)null);

                    b.HasDiscriminator().HasValue("Universitaire");
                });

            modelBuilder.Entity("SeminaPro.Models.Inscription", b =>
                {
                    b.HasOne("SeminaPro.Models.Participant", "Participant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeminaPro.Models.Seminaire", "Seminaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("SeminaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Seminaire");
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.HasOne("SeminaPro.Models.Specialite", "Specialite")
                        .WithMany("Participants")
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.HasOne("SeminaPro.Models.Specialite", "Specialite")
                        .WithMany("Seminaires")
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("SeminaPro.Models.Participant", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("SeminaPro.Models.Seminaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("SeminaPro.Models.Specialite", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Seminaires");
                });
#pragma warning restore 612, 618
        }
    }
}
